name: integration
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.10.16
  - conda-forge::jupyterlab=4.3.5
  - conda-forge::scanpy=1.10.4
  - conda-forge::anndata=0.11.3
  - anndata2ri
  - bbknn
  - bioconductor-singlecellexperiment
  - igraph
  - python-igraph
  - conda-forge::r-base
  - r-sessioninfo
  - r-seurat
  - r-spatstat
  - rpy2
  - scikit-learn=1.6.1
  - scikit-misc
  - scipy
  - scvi-tools=1.3.0
  - session-info
  - scib
